---
- name: Disable SELinux and firewalld on Linux systems
  hosts: frontend
  become: yes
  tasks:
    - name: Disable SELinux permanently
      lineinfile:
        path: /etc/selinux/config
        regexp: "^SELINUX="
        line: "SELINUX=disabled"

    - name: Enable NGINX repository
      ansible.builtin.shell: amazon-linux-extras enable nginx1
      become: true

    - name: Install NGINX
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Configure Nginx proxy
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx

    - name: Ensure NGINX is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes
      ignore_errors: yes  # Ignore this error temporarily to proceed and let handler take over

  handlers:
    - name: restart nginx
      block:
        - name: Test NGINX configuration
          command: nginx -t
          register: nginx_test
          failed_when: nginx_test.rc != 0
          changed_when: false

        - name: Restart NGINX if the configuration is valid
          service:
            name: nginx
            state: restarted
      when: nginx_test.rc == 0
