---
- name: Disable SELinux and firewalld on Linux systems
  hosts: frontend
  become: yes
  tasks:
    - name: Disable SELinux permanently
      lineinfile:
        path: /etc/selinux/config
        regexp: "^SELINUX="
        line: "SELINUX=disabled"
        
    - name: Update DNF repositories
      dnf:
        name: "*"
        state: latest

    - name: Enable NGINX repository
      ansible.builtin.shell: amazon-linux-extras enable nginx1
      become: true
    - name: Install Nginx
      dnf:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: true  # Start Nginx service on system boot
        
    - name: Configure Nginx proxy
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
