---
- name: Disable SELinux and firewalld on Linux systems
  hosts: frontend
  become: yes
  tasks:
    - name: Disable SELinux permanently
      lineinfile:
        path: /etc/selinux/config
        regexp: "^SELINUX="
        line: "SELINUX=disabled"

    - name: Enable NGINX repository
      ansible.builtin.shell: amazon-linux-extras enable nginx1
      become: true
    - name: Install NGINX
      ansible.builtin.yum:
        name: nginx
        state: present
      become: true
    - name: Configure NGINX as a proxy to Netdata
      copy:
        dest: /etc/nginx/conf.d/netdata_proxy.conf
        content: |
        server {
              listen 80;

              server_name {{ ansible_hostname }};  # Use the hostname or specify a domain name

              location / {
                  proxy_pass http://127.0.0.1:19999;  # Proxy to Netdata on port 19999
                  
              }
          }{
            proxy_pass http://u21.local:19999;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        error_page 404 /404.html;
        location = /404.html {
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        }
    }

  
      notify:
        - restart nginx      
      notify:
        - restart nginx
    - name: Ensure NGINX is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
